// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggiqpulqdmoazuievppt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnaXFwdWxxZG1vYXp1aWV2cHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTk4NzIsImV4cCI6MjA2NjY3NTg3Mn0.pfAmIULcv08GGgwLuu4eX79meIlHRPXNvKYUrq57GSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);